<a href="https://colab.research.google.com/github/GarvitPro/data-science-numpy-panda-solutions/blob/main/DS_TASK_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


data = np.arange(1, 36).reshape(7, 5)

df = pd.DataFrame(
    data,
    columns=['A', 'B', 'C', 'D', 'E']
)

print(df)

    A   B   C   D   E
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25
5  26  27  28  29  30
6  31  32  33  34  35

In [ ]:
df_add = df + 10
print(df_add)

    A   B   C   D   E
0  11  12  13  14  15
1  16  17  18  19  20
2  21  22  23  24  25
3  26  27  28  29  30
4  31  32  33  34  35
5  36  37  38  39  40
6  41  42  43  44  45

In [ ]:
df_sub = df - 5
print(df_sub)

    A   B   C   D   E
0  -4  -3  -2  -1   0
1   1   2   3   4   5
2   6   7   8   9  10
3  11  12  13  14  15
4  16  17  18  19  20
5  21  22  23  24  25
6  26  27  28  29  30

In [ ]:
df_mul = df * 2
print(df_mul)

    A   B   C   D   E
0   2   4   6   8  10
1  12  14  16  18  20
2  22  24  26  28  30
3  32  34  36  38  40
4  42  44  46  48  50
5  52  54  56  58  60
6  62  64  66  68  70

In [ ]:
df_div = df / 5
print(df_div)

     A    B    C    D    E
0  0.2  0.4  0.6  0.8  1.0
1  1.2  1.4  1.6  1.8  2.0
2  2.2  2.4  2.6  2.8  3.0
3  3.2  3.4  3.6  3.8  4.0
4  4.2  4.4  4.6  4.8  5.0
5  5.2  5.4  5.6  5.8  6.0
6  6.2  6.4  6.6  6.8  7.0

In [ ]:

df.loc[:, 'A' : 'C']

    A   B   C
0   1   2   3
1   6   7   8
2  11  12  13
3  16  17  18
4  21  22  23
5  26  27  28
6  31  32  33

In [ ]:
df.loc[:, 'B':'D']

    B   C   D
0   2   3   4
1   7   8   9
2  12  13  14
3  17  18  19
4  22  23  24
5  27  28  29
6  32  33  34

In [ ]:
df.iloc[:, 1:4]

    B   C   D
0   2   3   4
1   7   8   9
2  12  13  14
3  17  18  19
4  22  23  24
5  27  28  29
6  32  33  34